baseURL = 'https://ayeung.dev/'
languageCode = 'en-us'
title = 'ayeung.dev'
theme = "anubis2"
publishDir = "docs"

[params.author]
name = "Albert Au Yeung"
location = "Dublin, Ireland"

[pagination]
pagerSize = 20

[params]
copyCodeButton = true
rssAsSocialIcon = true
readMore = true
toc = false
math = true

colorTheme = "light"
colorThemeSwitcher = false

customCSS = ["custom-css/style.css"]

social = [
    { id = "github", url = "https://github.com/albertauyeung" },
    { id = "linkedin", url = "https://www.linkedin.com/in/albert-au-yeung/" },
]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
name = "Quotes"
identifier = "quotes"
url = "/quotes/"
weight = 4

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 5

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "base16-snazzy"
